version: '3'

services:
  zookeeper:
    image: zookeeper
    environment:
      ZOO_LOG4J_PROP: WARN

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      LOG4J_LOGGER_KAFKA: WARN
    depends_on:
      - zookeeper

  consul:
    image: consul
    command: agent -dev -client 0.0.0.0 -log-level warn

  config:
    image: viyadb/devenv
    volumes:
      - ./:/viyadb
    command: /viyadb/scripts/cluster_test/config.sh
    depends_on:
      - consul

  viyadb_1:
    image: viyadb/devenv
    volumes:
      - ./:/viyadb
    working_dir: /viyadb/build
    command: ./src/server/viyad ../scripts/cluster_test/node1.json
    depends_on:
      - kafka
      - consul

  viyadb_2:
    image: viyadb/devenv
    volumes:
      - ./:/viyadb
    working_dir: /viyadb/build
    command: ./src/server/viyad ../scripts/cluster_test/node1.json
    depends_on:
      - kafka
      - consul
