#!/bin/bash -eu

set -f

host=localhost
port=5000
if [ $# -ge 1 ]; then
  host=$1
  shift
fi
if [ $# -ge 1 ]; then
  port=$1
  shift
fi

export HISTCONTROL=ignoreboth:erasedups
history_file=~/.vsql_history
[[ -f $history_file ]] && history -n $history_file

tmpfile=$(mktemp)
trap "rm ${tmpfile}; history -w ${history_file}" EXIT

while IFS="" read -r -e -d $'\n' -p 'ViyaDB> ' query; do
  if [[ $? == 1 ]]; then
    echo
    break
  fi
  query="$(echo $query | sed 's/^\s*|\s*$//')"
  if [ ! -z "${query}" ]; then
    res=$(curl -L -sS -o ${tmpfile} -w '%{http_code}-%{time_total}' -d "${query}" http://${host}:${port}/sql?header)
    http_code=${res%-*}
    time_secs=${res#*-}
    if [ $http_code -eq 200 ]; then
      echo
      (head -1 $tmpfile; head -1 $tmpfile | sed 's/\S/-/g'; tail -n +2 $tmpfile) | column -s $'\t' -t
      echo
      echo "Time taken: ${time_secs} secs"
      echo
    else
      echo -n "ERROR: "
      echo -n $(cat $tmpfile); echo
    fi
    history -s "${query}"
  fi
done

